### PR TITLE
chore: update AviRecord to comply with updated x265 API

### LINKED ISSUE #760: AviRecord.cpp build failure with x265 4.0
**Describe the bug**
Build error with x265 4.0 (worked well with version 3.x)

**To Reproduce**
Build with x265 4.0
Here is the error:
```
/tmp/fceux-20240916-58775-96iqtc/src/drivers/Qt/AviRecord.cpp:463:8: error: no matching function for call to 'x265_encoder_encode'
ret = x265_encoder_encode( hdl, &nal, &i_nal, pic, &pic_out );
^~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/x265/4.0/include/x265.h:2496:5: note: candidate function not viable: no known conversion from 'x265_picture *' to 'x265_picture **' for 5th argument
int x265_encoder_encode(x265_encoder *encoder, x265_nal **pp_nal, uint32_t *pi_nal, x265_picture *pic_in, x265_picture **pic_out);
^
/tmp/fceux-20240916-58775-96iqtc/src/drivers/Qt/AviRecord.cpp:496:12: error: no matching function for call to 'x265_encoder_encode'
ret = x265_encoder_encode( hdl, &nal, &i_nal, NULL, &pic_out );
^~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/x265/4.0/include/x265.h:2496:5: note: candidate function not viable: no known conversion from 'x265_picture *' to 'x265_picture **' for 5th argument
int x265_encoder_encode(x265_encoder *encoder, x265_nal **pp_nal, uint32_t *pi_nal, x265_picture *pic_in, x265_picture **pic_out);
^
``` 

The change is in https://bitbucket.org/multicoreware/x265_git/commits/c69c113960834400545bc4bce2830ff51dcb86b3, the 5th argument changed from x265_picture *pic_out to x265_picture **pic_out

**Expected behavior**
No build error

**Screenshots**
Not applicable

**(please complete the following information):**
Not applicable

**Additional context**
See https://github.com/Homebrew/homebrew-core/pull/189134#issuecomment-2357564913

### PR DESCRIPTION
**Pull request by chenrui333**
fixes #760
relates to https://github.com/Homebrew/homebrew-core/pull/189134

### CODE REVIEW

File: src/drivers/Qt/AviRecord.cpp [hunk 1]
```diff
@@ -460,7 +460,8 @@ static int encode_frame( unsigned char *inBuf, int width, int height )
 	pic->stride[1] = width/2;
 	pic->stride[2] = width/2;
 
-	ret = x265_encoder_encode( hdl, &nal, &i_nal, pic, &pic_out );
+	x265_picture *pic_out = nullptr;
```
Comment (carlocab) [inline src/drivers/Qt/AviRecord.cpp:463]: Not sure this looks right. Aren't you shadowing

https://github.com/TASEmulators/fceux/blob/f980ec2bc7dc962f6cd76b9ae3131f2eb902c9e7/src/drivers/Qt/AviRecord.cpp#L272

?

**Comment by Cryolitia** [comment]
It should be an array instead of point of point.

see: https://code.videolan.org/videolan/vlc/-/merge_requests/6167
